blog_homepage:
    path:     /hello/{name}
    defaults: { _controller: BlogBundle:Default:index }
hoge:
    path: /
    defaults: { _controller: BlogBundle:Default:index }

blog_api:
  resource: "@BlogBundle/Controller/PostApiController.php"
  prefix: /api/
  type: rest

